In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(0,20,3) #(s,e,steps)

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
np.zeros(3) #1D

array([0., 0., 0.])

In [17]:
np.zeros([2,3]) #2D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0,5,50) #1-D evenly seperated array (start, end, number of points)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [25]:
np.eye(5) #Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(4)

array([0.06253799, 0.01828659, 0.70465317, 0.52850005])

In [28]:
np.random.rand(5,5)*4

array([[1.37955928, 1.38074904, 1.87943587, 1.76929419, 2.88012287],
       [1.81203364, 0.17096994, 2.16536666, 0.72859563, 1.13870226],
       [1.76443534, 3.34031029, 3.62022546, 0.0360363 , 0.58263871],
       [1.20082371, 0.14661334, 3.50344384, 2.24460733, 2.51339758],
       [3.86896959, 3.87041646, 3.63858883, 1.05619793, 1.34101287]])

In [30]:
np.random.randn(4,4) #

array([[ 0.18564501,  0.32171301,  1.1615923 , -1.69493242],
       [ 0.18996947,  0.84738875, -0.16357669,  0.05202741],
       [ 1.0124961 , -1.19210371,  0.21926091,  0.36985213],
       [ 0.90721712, -2.13781017, -0.76575325,  0.54895474]])

In [31]:
np.random.randint(1,100)

9

In [34]:
np.random.randint(1,100,10)

array([43, 32, 16, 82, 22,  8, 43, 58, 88, 64])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
rarr = np.random.randint(0,50,100)

In [47]:
rarr

array([ 1, 22,  7,  3, 30, 28,  2, 40, 32, 23, 14, 26, 32,  3, 46, 45, 26,
       39, 16, 33, 17,  0,  9, 40, 48, 19, 14, 36,  1,  2, 45, 49, 22, 43,
       38, 49, 22,  2, 46, 39, 29,  8, 44, 39, 32, 21, 42, 14, 30, 29, 44,
       45, 32, 24, 48, 31, 29, 15, 19, 36, 26,  4, 39,  0, 25,  7, 47,  4,
       33, 41, 21,  8,  5, 46, 34, 39,  2, 47, 33, 30, 11, 19, 29,  4, 15,
        5, 44, 18,  3, 20, 32,  3,  8, 44, 42, 34,  0, 42,  1, 45])

In [50]:
rarr.shape

(100,)

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
rarr.max() #max value

49

In [59]:
rarr.min()# min value

0

In [60]:
rarr

array([ 1, 22,  7,  3, 30, 28,  2, 40, 32, 23, 14, 26, 32,  3, 46, 45, 26,
       39, 16, 33, 17,  0,  9, 40, 48, 19, 14, 36,  1,  2, 45, 49, 22, 43,
       38, 49, 22,  2, 46, 39, 29,  8, 44, 39, 32, 21, 42, 14, 30, 29, 44,
       45, 32, 24, 48, 31, 29, 15, 19, 36, 26,  4, 39,  0, 25,  7, 47,  4,
       33, 41, 21,  8,  5, 46, 34, 39,  2, 47, 33, 30, 11, 19, 29,  4, 15,
        5, 44, 18,  3, 20, 32,  3,  8, 44, 42, 34,  0, 42,  1, 45])

In [66]:
rarr.argmin() #index of minvalue

21

In [67]:
rarr.argmax() #index of maxvalue

31

In [68]:
rarr.dtype


dtype('int64')

In [69]:
#indexing

In [70]:
ar = np.arange(0,11)

In [71]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
ar[1:5]

array([1, 2, 3, 4])

In [75]:
ar[5:] #slicing

array([ 5,  6,  7,  8,  9, 10])

In [76]:
ar[0:5] = 100

In [78]:
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
ar = np.arange(0,11)

In [80]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
slice_of_arr = ar[0:6] #sliced array

In [90]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [91]:
slice_of_arr[:] = 100 #Dont forget to add [:]

In [93]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [95]:
ar #when the slice is manipulated, the original is also changed

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [96]:
ar_copy = ar.copy()

In [97]:
ar_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [98]:
ar_copy[:] =100

In [99]:
ar_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [100]:
ar

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [101]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [102]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [104]:
arr_2d.shape

(3, 3)

In [105]:
arr_2d[0][0]

10

In [106]:
arr_2d[0]

array([10, 20, 30])

In [107]:
arr_2d[1][2] #python approach

60

In [109]:
arr_2d[1,2] #comma approach

60

In [111]:
arr_2d[:2,1:] #top right region

array([[20, 30],
       [50, 60]])

In [113]:
arr_2d[1:,:2] #bottom left

array([[40, 50],
       [70, 80]])

In [114]:
arr = np. arange(1,11)

In [115]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 5 #conditional selection

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [117]:
bool_array = arr > 5

In [118]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [120]:
arr[arr<3] #conditional selection in one step

array([1, 2])

In [123]:
arr_2d = np.arange(50).reshape(5,10)

In [124]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [126]:
arr_2d[arr_2d<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [128]:
#numpy operations

In [129]:
arr = np.arange(0,11)

In [133]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [134]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [135]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [137]:
arr + 100 #scalar operations

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [138]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [141]:
arr/arr #nan for divide by zero, no error just warning

/usr/local/Cellar/ipython/6.4.0/libexec/vendor/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [142]:
1/arr #infinity for 1/0

/usr/local/Cellar/ipython/6.4.0/libexec/vendor/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [143]:
arr **2 #exponents

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [144]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [145]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [146]:
np.max(arr) # or arr.max()

10

In [148]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [149]:
np.log(arr)

/usr/local/Cellar/ipython/6.4.0/libexec/vendor/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [150]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])